mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "LipNet Experiment"

data:
  download: False
  url: "https://drive.google.com/uc?id=1YlvpDLix3S-U8fd-gqRwPcWXAXm8JwjL"
  videos_path: "data/s1"
  lip_region_path: "data/lip_region/s1"
  label_path: "data/alignments/s1"
  padding: 10

seed: 42
batch_size: 4
num_workers: 0
pin_memory: True
input_channels: 3
hidden_size: 256
dropout: 0.5
lr: 0.00002 # 2e-5
weight_decay: 0.00001 # 1e-5
num_epochs: 1
checkpoint_path: "checkpoints/"
prev_checkpoint: 
print_every: 10
new_lr: 0.00001 # 1e-5
val_split_ratio: 0.2
test_split_ratio: 0.1
model_name: "LipNetModel"